// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAypOVBZYCwS0nPkPvmJF4aMPhXN56FS00',
//     appId: '1:73773520811:web:b1cf74e878ea53c5a1e4ee',
//     messagingSenderId: '73773520811',
//     projectId: 'map-38ed1',
//     authDomain: 'map-38ed1.firebaseapp.com',
//     storageBucket: 'map-38ed1.appspot.com',
//     measurementId: 'G-PZW308H38F',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDuF7p8QAg8zi1l35lpivUjWQ9aQJ2MNLs',
//     appId: '1:73773520811:android:4f31232de42bccd5a1e4ee',
//     messagingSenderId: '73773520811',
//     projectId: 'map-38ed1',
//     storageBucket: 'map-38ed1.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAIEAb8gxLWk4PblA5LP6M1LMqInllshC8',
//     appId: '1:73773520811:ios:ab2772e38363553ba1e4ee',
//     messagingSenderId: '73773520811',
//     projectId: 'map-38ed1',
//     storageBucket: 'map-38ed1.appspot.com',
//     iosClientId: '73773520811-v9faog21du68bt899temcn44e67c65vh.apps.googleusercontent.com',
//     iosBundleId: 'com.example.googleMap',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAIEAb8gxLWk4PblA5LP6M1LMqInllshC8',
//     appId: '1:73773520811:ios:ab2772e38363553ba1e4ee',
//     messagingSenderId: '73773520811',
//     projectId: 'map-38ed1',
//     storageBucket: 'map-38ed1.appspot.com',
//     iosClientId: '73773520811-v9faog21du68bt899temcn44e67c65vh.apps.googleusercontent.com',
//     iosBundleId: 'com.example.googleMap',
//   );
// }
